late_fusion_node:
  ros__parameters:
    image_input_topic: "/camera/image_raw"
    image_detections_topic: "yolo/detections"
    lidar_detections_topic: "lidar/detections"
    calibration_topic: "/camera/calibration"

    fussed_publisher_topic: "deepfusion/matching"
    unmatched_3d_publisher_topic: "deepfusion/nonmatching_3d"
    unmatched_2d_publisher_topic: "deepfusion/nonmatching_2d"


projection_node:
  ros__parameters:
    input_matching_topic: "deepfusion/matching"
    input_nonmatching_topic: "deepfusion/nonmatching"
    input_image_topic: "camera/image_raw"
